"""Canonical event-kind metadata shared with the React application.

This module is deliberately pure data so it can be exported as JSON without an
application context. Per-event values (dates, prices and coordinates) remain on
``Post``; this registry describes stable defaults and supported presentation
features. Weekdays follow Python's convention: Monday=0 through Sunday=6.
"""

EVENT_KIND_SCHEMA_VERSION = 2

EVENT_KINDS = {
    "country_evening": {
        "id": "country_evening",
        "label": {"en": "Country Evening", "de": "Länderabend"},
        "icon": "globe",
        "marker": "bad",
        "titlePrefix": {"en": "Country Evening", "de": "Länderabend"},
        "highlightTitle": True,
        "schedule": {"weekday": 1, "time": "20:00"},
        "mapMode": "country",
        "features": ["map"],
        "registrationDefault": False,
        "depositDefault": False,
        "defaultCapacity": None,
        "defaultPriceCents": None,
        "defaultDurationMinutes": 240,
        "registrationMode": "none",
        "calendarPresentation": "highlight",
        "landingPresentation": "featured",
    },
    "cafe_lingua": {
        "id": "cafe_lingua",
        "label": {"en": "Café Lingua", "de": "Café Lingua"},
        "icon": "chat",
        "marker": "accent",
        "titlePrefix": None,
        "highlightTitle": False,
        "schedule": {"weekday": 1, "time": "20:00"},
        "mapMode": "venue",
        "features": ["map"],
        "registrationDefault": False,
        "depositDefault": False,
        "defaultCapacity": None,
        "defaultPriceCents": None,
        "defaultDurationMinutes": 240,
        "registrationMode": "none",
        "calendarPresentation": "highlight",
        "landingPresentation": "standard",
    },
    "board_games": {
        "id": "board_games",
        "label": {"en": "Board Games", "de": "Brettspielabende"},
        "icon": "dice",
        "marker": "ok",
        "titlePrefix": None,
        "highlightTitle": False,
        "schedule": {"weekday": 1, "time": "20:00"},
        "mapMode": "venue",
        "features": ["map"],
        "registrationDefault": False,
        "depositDefault": False,
        "defaultCapacity": None,
        "defaultPriceCents": None,
        "defaultDurationMinutes": 240,
        "registrationMode": "none",
        "calendarPresentation": "highlight",
        "landingPresentation": "standard",
    },
    "karaoke": {
        "id": "karaoke",
        "label": {"en": "Karaoke", "de": "Karaoke"},
        "icon": "mic",
        "marker": "warn",
        "titlePrefix": None,
        "highlightTitle": False,
        "schedule": {"weekday": 1, "time": "20:00"},
        "mapMode": "venue",
        "features": ["karaoke_queue", "map"],
        "registrationDefault": False,
        "depositDefault": False,
        "defaultCapacity": None,
        "defaultPriceCents": None,
        "defaultDurationMinutes": 240,
        "registrationMode": "karaoke",
        "calendarPresentation": "highlight",
        "landingPresentation": "featured",
    },
    "dance": {
        "id": "dance",
        "label": {"en": "Dance Workshops", "de": "Tanzworkshops"},
        "icon": "music",
        "marker": "info",
        "titlePrefix": None,
        "highlightTitle": False,
        "schedule": {"weekday": 1, "time": "20:00"},
        "mapMode": "venue",
        "features": ["map"],
        "registrationDefault": False,
        "depositDefault": False,
        "defaultCapacity": None,
        "defaultPriceCents": None,
        "defaultDurationMinutes": 240,
        "registrationMode": "none",
        "calendarPresentation": "highlight",
        "landingPresentation": "standard",
    },
    "breakfast": {
        "id": "breakfast",
        "label": {"en": "International Breakfast", "de": "Internationales Frühstück"},
        "icon": "egg",
        "marker": "muted",
        "titlePrefix": {"en": "International Breakfast", "de": "Internationales Frühstück"},
        "highlightTitle": True,
        "schedule": {"weekday": 5, "time": "10:00"},
        "mapMode": "venue",
        "features": ["registration", "deposit", "map"],
        "registrationDefault": True,
        "depositDefault": True,
        "defaultCapacity": 40,
        "defaultPriceCents": 200,
        "defaultDurationMinutes": 180,
        "registrationMode": "queue",
        "calendarPresentation": "highlight",
        "landingPresentation": "featured",
    },
    "trip": {
        "id": "trip",
        "label": {"en": "International Weekend", "de": "Internationales Wochenende"},
        "icon": "signpost",
        "marker": "ink",
        "titlePrefix": {"en": "International Weekend", "de": "Internationales Wochenende"},
        "highlightTitle": False,
        "schedule": {"weekday": 5, "time": "09:00"},
        "mapMode": "destination",
        "features": ["registration", "map"],
        "registrationDefault": True,
        "depositDefault": False,
        "defaultCapacity": 80,
        "defaultPriceCents": 2500,
        "defaultDurationMinutes": 600,
        "registrationMode": "queue",
        "calendarPresentation": "highlight",
        "landingPresentation": "featured",
    },
    "international_tuesday": {
        "id": "international_tuesday",
        "label": {"en": "International Tuesday", "de": "Internationaler Dienstag"},
        "icon": "people",
        "marker": "accent",
        "titlePrefix": None,
        "highlightTitle": False,
        "schedule": {"weekday": 1, "time": "20:00"},
        "mapMode": "venue",
        "features": ["map"],
        "registrationDefault": False,
        "depositDefault": False,
        "defaultCapacity": None,
        "defaultPriceCents": None,
        "defaultDurationMinutes": 240,
        "registrationMode": "none",
        "calendarPresentation": "highlight",
        "landingPresentation": "standard",
    },
    "incas_active": {
        "id": "incas_active",
        "label": {"en": "INCAS Active", "de": "INCAS Aktiv"},
        "icon": "activity",
        "marker": "ok",
        "titlePrefix": None,
        "highlightTitle": False,
        "schedule": None,
        "mapMode": "venue",
        "features": ["map"],
        "registrationDefault": False,
        "depositDefault": False,
        "defaultCapacity": None,
        "defaultPriceCents": None,
        "defaultDurationMinutes": 180,
        "registrationMode": "none",
        "calendarPresentation": "highlight",
        "landingPresentation": "standard",
    },
    "opening_ceremony": {
        "id": "opening_ceremony",
        "label": {"en": "Opening Ceremony", "de": "Eröffnungsfeier"},
        "icon": "sparkles",
        "marker": "accent",
        "titlePrefix": None,
        "highlightTitle": False,
        "schedule": None,
        "mapMode": "venue",
        "features": ["map"],
        "registrationDefault": False,
        "depositDefault": False,
        "defaultCapacity": None,
        "defaultPriceCents": None,
        "defaultDurationMinutes": 180,
        "registrationMode": "none",
        "calendarPresentation": "highlight",
        "landingPresentation": "featured",
    },
    "housing": {
        "id": "housing",
        "label": {"en": "Housing", "de": "Wohnen"},
        "icon": "house",
        "marker": "muted",
        "titlePrefix": None,
        "highlightTitle": False,
        "schedule": None,
        "mapMode": "none",
        "features": [],
        "registrationDefault": False,
        "depositDefault": False,
        "defaultCapacity": None,
        "defaultPriceCents": None,
        "defaultDurationMinutes": 120,
        "registrationMode": "none",
        "calendarPresentation": "standard",
        "landingPresentation": "standard",
    },
}


def get_event_kind(kind_id):
    return EVENT_KINDS.get(kind_id)


def event_kind_ids():
    return list(EVENT_KINDS.keys())
