"""baseline React migration schema

Revision ID: 1e2379697b4a
Revises: 
Create Date: 2026-07-11 22:03:20.212119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2379697b4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_keys_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_keys_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_access_keys_revoked_at'), ['revoked_at'], unique=False)

    op.create_table('contact_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_viewed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_requests_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_requests_is_viewed'), ['is_viewed'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_requests_status'), ['status'], unique=False)

    op.create_table('event_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('contact_name', sa.String(length=160), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=80), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_viewed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_suggestions_contact_email'), ['contact_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_suggestions_is_viewed'), ['is_viewed'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_suggestions_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_suggestions_status'), ['status'], unique=False)

    op.create_table('instagram_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ig_user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instagram_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instagram_connections_ig_user_id'), ['ig_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instagram_connections_is_active'), ['is_active'], unique=False)

    op.create_table('language_tandem_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('occupation', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=40), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('country_of_origin', sa.String(length=120), nullable=False),
    sa.Column('offered_languages', sa.Text(), nullable=False),
    sa.Column('offered_native_languages', sa.Text(), nullable=False),
    sa.Column('offered_language_levels', sa.Text(), nullable=False),
    sa.Column('requested_languages', sa.Text(), nullable=False),
    sa.Column('requested_native_only', sa.Boolean(), nullable=False),
    sa.Column('same_gender_only', sa.Boolean(), nullable=False),
    sa.Column('preferred_gender', sa.String(length=40), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_viewed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('language_tandem_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_language_tandem_requests_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_language_tandem_requests_is_viewed'), ['is_viewed'], unique=False)

    op.create_table('page_theme_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=False),
    sa.Column('previous_theme', sa.String(length=64), nullable=False),
    sa.Column('new_theme', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_theme_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_theme_audits_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_theme_audits_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_theme_audits_page_id'), ['page_id'], unique=False)

    op.create_table('page_theme_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=False),
    sa.Column('theme_id', sa.String(length=64), nullable=False),
    sa.Column('last_forced_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_theme_selections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_theme_selections_page_id'), ['page_id'], unique=True)

    op.create_table('page_theme_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=False),
    sa.Column('theme_id', sa.String(length=64), nullable=False),
    sa.Column('voter_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'voter_id', name='uq_page_theme_vote_voter')
    )
    with op.batch_alter_table('page_theme_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_theme_votes_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_theme_votes_voter_id'), ['voter_id'], unique=False)

    op.create_table('post_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('title_pattern', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('event_kind', sa.String(length=64), nullable=True),
    sa.Column('registration_limit_enabled', sa.Boolean(), nullable=False),
    sa.Column('registration_limit', sa.Integer(), nullable=True),
    sa.Column('registration_price_cents', sa.Integer(), nullable=True),
    sa.Column('registration_is_deposit', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('social_settings', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('publish_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('event_kind', sa.String(length=64), nullable=True),
    sa.Column('registration_limit_enabled', sa.Boolean(), nullable=False),
    sa.Column('registration_limit', sa.Integer(), nullable=True),
    sa.Column('registration_price_cents', sa.Integer(), nullable=True),
    sa.Column('registration_is_deposit', sa.Boolean(), nullable=False),
    sa.Column('registration_mode', sa.String(length=32), nullable=False),
    sa.Column('deposit_explanation', sa.String(length=500), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('meeting_point', sa.String(length=300), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('destination_latitude', sa.Float(), nullable=True),
    sa.Column('destination_longitude', sa.Float(), nullable=True),
    sa.Column('map_config', sa.Text(), nullable=False),
    sa.Column('feature_flags', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('instagram_media_id', sa.String(length=64), nullable=False),
    sa.Column('instagram_permalink', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_event_kind'), ['event_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_instagram_media_id'), ['instagram_media_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_is_pinned'), ['is_pinned'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_publish_at'), ['publish_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_registration_limit_enabled'), ['registration_limit_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_posts_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_status'), ['status'], unique=False)

    op.create_table('tandem_duplicate_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('left_request_id', sa.Integer(), nullable=False),
    sa.Column('right_request_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('left_request_id', 'right_request_id', name='uq_tandem_duplicate_decision_pair')
    )
    with op.batch_alter_table('tandem_duplicate_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tandem_duplicate_decisions_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_tandem_duplicate_decisions_left_request_id'), ['left_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tandem_duplicate_decisions_right_request_id'), ['right_request_id'], unique=False)

    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('occupation', sa.String(length=120), nullable=False),
    sa.Column('diet_preference', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_registrations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_registrations_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_registrations_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_registrations_status'), ['status'], unique=False)

    op.create_table('karaoke_song_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('song_title', sa.String(length=200), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('karaoke_song_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_karaoke_song_requests_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_karaoke_song_requests_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_karaoke_song_requests_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_karaoke_song_requests_status'), ['status'], unique=False)

    op.create_table('social_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_post_id', sa.String(length=64), nullable=False),
    sa.Column('permalink', sa.String(length=500), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_publications_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_publications_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_publications_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_publications_status'), ['status'], unique=False)

    op.create_table('tandem_match_review_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_request_id', sa.Integer(), nullable=False),
    sa.Column('candidate_request_id', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_shortlisted', sa.Boolean(), nullable=False),
    sa.Column('contacted_at', sa.DateTime(), nullable=True),
    sa.Column('final_pair_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_request_id'], ['language_tandem_requests.id'], ),
    sa.ForeignKeyConstraint(['source_request_id'], ['language_tandem_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_request_id', 'candidate_request_id', name='uq_tandem_match_review_state_pair')
    )
    with op.batch_alter_table('tandem_match_review_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tandem_match_review_states_candidate_request_id'), ['candidate_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tandem_match_review_states_source_request_id'), ['source_request_id'], unique=False)

    op.create_table('karaoke_queue_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['karaoke_song_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('karaoke_queue_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_karaoke_queue_audits_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_karaoke_queue_audits_request_id'), ['request_id'], unique=False)

    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_session_id', sa.String(length=128), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['event_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transactions_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_transactions_registration_id'), ['registration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_registration_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_public_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_post_id'))

    op.drop_table('payment_transactions')
    with op.batch_alter_table('karaoke_queue_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_karaoke_queue_audits_request_id'))
        batch_op.drop_index(batch_op.f('ix_karaoke_queue_audits_created_at'))

    op.drop_table('karaoke_queue_audits')
    with op.batch_alter_table('tandem_match_review_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tandem_match_review_states_source_request_id'))
        batch_op.drop_index(batch_op.f('ix_tandem_match_review_states_candidate_request_id'))

    op.drop_table('tandem_match_review_states')
    with op.batch_alter_table('social_publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_publications_status'))
        batch_op.drop_index(batch_op.f('ix_social_publications_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_social_publications_provider'))
        batch_op.drop_index(batch_op.f('ix_social_publications_post_id'))

    op.drop_table('social_publications')
    with op.batch_alter_table('karaoke_song_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_karaoke_song_requests_status'))
        batch_op.drop_index(batch_op.f('ix_karaoke_song_requests_public_id'))
        batch_op.drop_index(batch_op.f('ix_karaoke_song_requests_post_id'))
        batch_op.drop_index(batch_op.f('ix_karaoke_song_requests_position'))

    op.drop_table('karaoke_song_requests')
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_registrations_status'))
        batch_op.drop_index(batch_op.f('ix_event_registrations_public_id'))
        batch_op.drop_index(batch_op.f('ix_event_registrations_post_id'))
        batch_op.drop_index(batch_op.f('ix_event_registrations_email'))

    op.drop_table('event_registrations')
    with op.batch_alter_table('tandem_duplicate_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tandem_duplicate_decisions_right_request_id'))
        batch_op.drop_index(batch_op.f('ix_tandem_duplicate_decisions_left_request_id'))
        batch_op.drop_index(batch_op.f('ix_tandem_duplicate_decisions_decision'))

    op.drop_table('tandem_duplicate_decisions')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_status'))
        batch_op.drop_index(batch_op.f('ix_posts_starts_at'))
        batch_op.drop_index(batch_op.f('ix_posts_slug'))
        batch_op.drop_index(batch_op.f('ix_posts_registration_limit_enabled'))
        batch_op.drop_index(batch_op.f('ix_posts_publish_at'))
        batch_op.drop_index(batch_op.f('ix_posts_is_pinned'))
        batch_op.drop_index(batch_op.f('ix_posts_is_active'))
        batch_op.drop_index(batch_op.f('ix_posts_instagram_media_id'))
        batch_op.drop_index(batch_op.f('ix_posts_event_kind'))

    op.drop_table('posts')
    op.drop_table('post_templates')
    with op.batch_alter_table('page_theme_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_theme_votes_voter_id'))
        batch_op.drop_index(batch_op.f('ix_page_theme_votes_page_id'))

    op.drop_table('page_theme_votes')
    with op.batch_alter_table('page_theme_selections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_theme_selections_page_id'))

    op.drop_table('page_theme_selections')
    with op.batch_alter_table('page_theme_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_theme_audits_page_id'))
        batch_op.drop_index(batch_op.f('ix_page_theme_audits_created_at'))
        batch_op.drop_index(batch_op.f('ix_page_theme_audits_action'))

    op.drop_table('page_theme_audits')
    with op.batch_alter_table('language_tandem_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_language_tandem_requests_is_viewed'))
        batch_op.drop_index(batch_op.f('ix_language_tandem_requests_email'))

    op.drop_table('language_tandem_requests')
    with op.batch_alter_table('instagram_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instagram_connections_is_active'))
        batch_op.drop_index(batch_op.f('ix_instagram_connections_ig_user_id'))

    op.drop_table('instagram_connections')
    with op.batch_alter_table('event_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_event_suggestions_kind'))
        batch_op.drop_index(batch_op.f('ix_event_suggestions_is_viewed'))
        batch_op.drop_index(batch_op.f('ix_event_suggestions_contact_email'))

    op.drop_table('event_suggestions')
    with op.batch_alter_table('contact_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_requests_status'))
        batch_op.drop_index(batch_op.f('ix_contact_requests_is_viewed'))
        batch_op.drop_index(batch_op.f('ix_contact_requests_email'))

    op.drop_table('contact_requests')
    with op.batch_alter_table('access_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_keys_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_access_keys_key'))
        batch_op.drop_index(batch_op.f('ix_access_keys_expires_at'))

    op.drop_table('access_keys')
    # ### end Alembic commands ###
